### ISSUE TITLE
Gender neutrality on home page

### ISSUE THREAD

**Issue by PhillyUrbs** [Rem0o/FanControl.Website#7]
A teammate took issue with the non-gender neutrality of the site preview that is loaded by some applications when linking to getfancontrol.com

on getfancontrol.com change the following line from

"Fan Control is a free software that allows the user to control his CPU, GPU and case fans using temperatures."

to 

Fan Control is a free software that allows the user to control **their** CPU, GPU and case fans using temperatures.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Website/commit/7214d2b454550a8143bbcfbe03a6c3fa558eeb4d
