### ISSUE TITLE
Side menu items hidden until the users scrolls to the bottom of the page

### ISSUE THREAD

**Issue by stamminator** [Rem0o/FanControl.Website#8]
I kept going to the documentation page to find which command line parameters I could use, but wasn't finding them. Only upon scrolling all the way to the bottom did the side menu options overflowing past the viewport become visible.

![Animation](https://github.com/user-attachments/assets/f1eceefe-4883-484b-8ed8-34480a2269b5)

A fix for this could be for the left menu to be independently scrollable with a visible scrollbar, which tells the user that there is more content below. The https://angular.dev/overview site provides a good example.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Website/commit/8478869fe585d44093168668872ce7ba3f00334e

**Comment by stamminator** [comment]
@Rem0o Looks great! That div can probably use `pr-2` or `pr-3` for some space, but it's fine either way.

![BxvAv97EvN (Phone)](https://github.com/user-attachments/assets/84e4924a-a69e-451f-821b-8581904e8ad4)

**Comment by Rem0o** [comment]
Done.
